services:
  meetup_api:
    build: ./app
    command: uvicorn main:app --reload --host 0.0.0.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=postgres
    networks:
      - meetup_nw
    ports:
      - "80:8000"

  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - meetup_nw
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}

networks:
  meetup_nw: {}